export const products = [
  {
    id: 1,
    name: "Tomate Big Beef",
    category: "Tomates",
    image: "big-beef.jpg",
    isDeterminate: false,
    isFavorite: false,
  },
  {
    id: 2,
    name: "Tomate Jasper",
    category: "Tomates",
    image: "jasper.jpg",
    isDeterminate: false,
    isFavorite: false,
  },
  {
    id: 3,
    name: "Tomate Roma",
    category: "Tomates",
    image: "roma.jpg",
    isDeterminate: true,
    isFavorite: false,
  },
  {
    id: 4,
    name: "Tomate Blue Cream",
    category: "Tomates",
    image: "blue-cream.jpg",
    isDeterminate: false,
    isFavorite: false,
  },
  {
    id: 5,
    name: "Tomate Principe Borghese",
    category: "Tomates",
    image: "principe-borghese.jpg",
    isDeterminate: true,
    isFavorite: false,
  },
  {
    id: 6,
    name: "Tomate Beefsteak",
    category: "Tomates",
    image: "beefsteak.jpg",
    isDeterminate: false,
    isFavorite: false,
  },
  {
    id: 7,
    name: "Tomate Black Cherry",
    category: "Tomates",
    image: "black-cherry.jpg",
    isDeterminate: false,
    isFavorite: false,
  },
  {
    id: 8,
    name: "Tomate Taxi",
    category: "Tomates",
    image: "taxi.jpg",
    isDeterminate: true,
    isFavorite: false,
  },
  {
    id: 9,
    name: "Tomate Millefleur",
    category: "Tomates",
    image: "millefleur.jpg",
    isDeterminate: false,
    isFavorite: true,
  },
  {
    id: 10,
    name: "Tomate Candyland",
    category: "Tomates",
    image: "candyland.jpg",
    isDeterminate: false,
    isFavorite: false,
  },
  {
    id: 11,
    name: "Tomate Sungold",
    category: "Tomates",
    image: "sungold.jpg",
    isDeterminate: false,
    isFavorite: true,
  },
  {
    id: 12,
    name: "Tomate Black Krim",
    category: "Tomates",
    image: "black-krim.jpg",
    isDeterminate: false,
    isFavorite: false,
  },
  {
    id: 13,
    name: "Tomate Ace 55",
    category: "Tomates",
    image: "ace-55.jpg",
    isDeterminate: true,
  },
  {
    id: 14,
    name: "Tomate Brandywine",
    category: "Tomates",
    image: "brandywine.jpg",
    isDeterminate: false,
    isFavorite: false,
  },
  {
    id: 15,
    name: "Tomate Green Zebra",
    category: "Tomates",
    image: "green-zebra.jpg",
    isDeterminate: false,
    isFavorite: false,
  },
  {
    id: 16,
    name: "Tomate San Marzano",
    category: "Tomates",
    image: "san-marzano.jpg",
    isDeterminate: false,
    isFavorite: false,
  },
  {
    id: 17,
    name: "Tomate Chef's Choice Orange",
    category: "Tomates",
    image: "chefs-choice-orange.jpg",
    isDeterminate: false,
    isFavorite: false,
  },
  {
    id: 18,
    name: "Tomate Clementine",
    category: "Tomates",
    image: "clementine.jpg",
    isDeterminate: false,
    isFavorite: false,
  },
  {
    id: 19,
    name: "Tomate Pink Cupcake",
    category: "Tomates",
    image: "pink-cupcake.jpg",
    isDeterminate: true,
    isFavorite: false,
  },
  {
    id: 20,
    name: "Concombre Summer Dance",
    category: "Concombres",
    image: "summer-dance.jpg",
    isFavorite: false,
  },
  {
    id: 21,
    name: "Concombre Marketmore 76",
    category: "Concombres",
    image: "marketmore-76.jpg",
    isFavorite: false,
  },
  {
    id: 22,
    name: "Concombre National Pickling",
    category: "Concombres",
    image: "national-pickling.jpg",
    isFavorite: false,
  },
  {
    id: 23,
    name: "Cerise de terre Aunt Molly’s",
    category: "Fruits",
    image: "aunt-mollys.jpg",
    isFavorite: false,
  },
  {
    id: 24,
    name: "Basilic Genovese",
    category: "Herbes",
    image: "genovese-basil.jpg",
    isFavorite: false,
  },
  {
    id: 25,
    name: "Basilic Siam Queen",
    category: "Herbes",
    image: "siam-queen-basil.jpg",
    isFavorite: false,
  },
  {
    id: 26,
    name: "Basilic Licorice",
    category: "Herbes",
    image: "licorice-basil.jpg",
    isFavorite: false,
  },
  {
    id: 27,
    name: "Basilic Cinnamon",
    category: "Herbes",
    image: "cinnamon-basil.jpg",
    isFavorite: false,
  },
  {
    id: 28,
    name: "Basilic Freddy Red",
    category: "Herbes",
    image: "freddy-red-basil.jpg",
    isFavorite: false,
  },
  {
    id: 29,
    name: "Sauge",
    category: "Herbes",
    image: "sauge.jpg",
    isFavorite: false,
  },
  {
    id: 30,
    name: "Zucchini Black Beauty",
    category: "Courges",
    image: "black-beauty-zucchini.jpg",
    isFavorite: false,
  },
  {
    id: 31,
    name: "Zucchini Cocozelle",
    category: "Courges",
    image: "cocozelle-zucchini.jpg",
    isFavorite: false,
  },
  {
    id: 32,
    name: "Zucchini Italian Striped",
    category: "Courges",
    image: "italian-striped-zucchini.jpg",
    isFavorite: false,
  },
  {
    id: 33,
    name: "Zucchini Spineless Perfection",
    category: "Courges",
    image: "spineless-perfection-zucchini.jpg",
    isFavorite: false,
  },
  {
    id: 34,
    name: "Zucchini Eight Ball",
    category: "Courges",
    image: "eight-ball-zucchini.jpg",
    isFavorite: false,
  },
  {
    id: 35,
    name: "Courge Spaghetti",
    category: "Courges",
    image: "spaghetti-squash.jpg",
    isFavorite: false,
  },
  {
    id: 36,
    name: "Courge Butternut Waltham",
    category: "Courges",
    image: "waltham-butternut.jpg",
    isFavorite: false,
  },
  {
    id: 37,
    name: "Tomate Blush",
    category: "Tomates",
    image: "blush.jpg",
    isDeterminate: false,
    isFavorite: false,
  },
  {
    id: 38,
    name: "Tomatillo Rio Grande Verde",
    category: "Tomatillos",
    image: "rio-grande-verde-tomatillo.jpg",
    isFavorite: false,
  },
  {
    id: 39,
    name: "Tomatillo Mauve",
    category: "Tomatillos",
    image: "purple-tomatillo.jpg",
    isFavorite: false,
  },
  {
    id: 40,
    name: "Aubergine Patio Baby",
    category: "Aubergines",
    image: "patio-baby-eggplant.jpg",
    isFavorite: false,
  },
];
