export const products = [
  {
    id: 1,
    name: "Big Beef",
    category: "tomatoes",
    image: "big-beef.jpg",
    isDeterminate: false,
    isFavorite: false,
  },
  {
    id: 2,
    name: "Jasper",
    category: "tomatoes",
    image: "jasper.jpg",
    isDeterminate: false,
    isFavorite: false,
  },
  {
    id: 3,
    name: "Roma",
    category: "tomatoes",
    image: "roma.jpg",
    isDeterminate: true,
    isFavorite: false,
  },
  {
    id: 4,
    name: "Blue Cream",
    category: "tomatoes",
    image: "blue-cream.jpg",
    isDeterminate: false,
    isFavorite: false,
  },
  {
    id: 5,
    name: "Principe Borghese",
    category: "tomatoes",
    image: "principe-borghese.jpg",
    isDeterminate: true,
    isFavorite: false,
  },
  {
    id: 6,
    name: "Beefsteak",
    category: "tomatoes",
    image: "beefsteak.jpg",
    isDeterminate: false,
    isFavorite: false,
  },
  {
    id: 7,
    name: "Black Cherry",
    category: "tomatoes",
    image: "black-cherry.jpg",
    isDeterminate: false,
    isFavorite: false,
  },
  {
    id: 8,
    name: "Taxi",
    category: "tomatoes",
    image: "taxi.jpg",
    isDeterminate: true,
    isFavorite: false,
  },
  {
    id: 9,
    name: "Millefleur",
    category: "tomatoes",
    image: "millefleur.jpg",
    isDeterminate: false,
    isFavorite: true,
  },
  {
    id: 10,
    name: "Candyland",
    category: "tomatoes",
    image: "candyland.jpg",
    isDeterminate: false,
    isFavorite: false,
  },
  {
    id: 11,
    name: "Sungold",
    category: "tomatoes",
    image: "sungold.jpg",
    isDeterminate: false,
    isFavorite: true,
  },
  {
    id: 12,
    name: "Black Krim",
    category: "tomatoes",
    image: "black-krim.jpg",
    isDeterminate: false,
    isFavorite: false,
  },
  {
    id: 13,
    name: "Ace 55",
    category: "tomatoes",
    image: "ace-55.jpg",
    isDeterminate: true,
  },
  {
    id: 14,
    name: "Brandywine",
    category: "tomatoes",
    image: "brandywine.jpg",
    isDeterminate: false,
    isFavorite: false,
  },
  {
    id: 15,
    name: "Green Zebra",
    category: "tomatoes",
    image: "green-zebra.jpg",
    isDeterminate: false,
    isFavorite: false,
  },
  {
    id: 16,
    name: "San Marzano",
    category: "tomatoes",
    image: "san-marzano.jpg",
    isDeterminate: false,
    isFavorite: false,
  },
  {
    id: 17,
    name: "Chef's Choice Orange",
    category: "tomatoes",
    image: "chefs-choice-orange.jpg",
    isDeterminate: false,
    isFavorite: false,
  },
  {
    id: 18,
    name: "Clementine",
    category: "tomatoes",
    image: "clementine.jpg",
    isDeterminate: false,
    isFavorite: false,
  },
  {
    id: 19,
    name: "Pink Cupcake",
    category: "tomatoes",
    image: "pink-cupcake.jpg",
    isDeterminate: true,
    isFavorite: false,
  },
  {
    id: 20,
    name: "Summer Dance",
    category: "cucumbers",
    image: "summer-dance.jpg",
    isFavorite: false,
  },
  {
    id: 21,
    name: "Marketmore 76",
    category: "cucumbers",
    image: "marketmore-76.jpg",
    isFavorite: false,
  },
  {
    id: 22,
    name: "National Pickling",
    category: "cucumbers",
    image: "national-pickling.jpg",
    isFavorite: false,
  },
  {
    id: 23,
    name: "Aunt Molly’s",
    category: "fruits",
    image: "aunt-mollys.jpg",
    isFavorite: false,
  },
  {
    id: 24,
    name: "Genovese Basil",
    category: "herbs",
    image: "genovese-basil.jpg",
    isFavorite: false,
  },
  {
    id: 25,
    name: "Siam Queen Basil",
    category: "herbs",
    image: "siam-queen-basil.jpg",
    isFavorite: false,
  },
  {
    id: 26,
    name: "Licorice Basil",
    category: "herbs",
    image: "licorice-basil.jpg",
    isFavorite: false,
  },
  {
    id: 27,
    name: "Cinnamon Basil",
    category: "herbs",
    image: "cinnamon-basil.jpg",
    isFavorite: false,
  },
  {
    id: 28,
    name: "Freddy Red Basil",
    category: "herbs",
    image: "freddy-red-basil.jpg",
    isFavorite: false,
  },
  {
    id: 29,
    name: "Sauge",
    category: "herbs",
    image: "sauge.jpg",
    isFavorite: false,
  },
  {
    id: 30,
    name: "Black Beauty Zucchini",
    category: "squash",
    image: "black-beauty-zucchini.jpg",
    isFavorite: false,
  },
  {
    id: 31,
    name: "Cocozelle Zucchini",
    category: "squash",
    image: "cocozelle-zucchini.jpg",
    isFavorite: false,
  },
  {
    id: 32,
    name: "Italian Striped Zucchini",
    category: "squash",
    image: "italian-striped-zucchini.jpg",
    isFavorite: false,
  },
  {
    id: 33,
    name: "Spineless Perfection Zucchini",
    category: "squash",
    image: "spineless-perfection-zucchini.jpg",
    isFavorite: false,
  },
  {
    id: 34,
    name: "Eight Ball Zucchini",
    category: "squash",
    image: "eight-ball-zucchini.jpg",
    isFavorite: false,
  },
  {
    id: 35,
    name: "Spaghetti Squash",
    category: "squash",
    image: "spaghetti-squash.jpg",
    isFavorite: false,
  },
  {
    id: 36,
    name: "Waltham Butternut",
    category: "squash",
    image: "waltham-butternut.jpg",
    isFavorite: false,
  },
  {
    id: 37,
    name: "Blush",
    category: "tomato",
    image: "blush.jpg",
    isDeterminate: false,
    isFavorite: false,
  },
];
